### ISSUE TITLE
Not able to transfer polyx on dev node

### ISSUE THREAD

**Issue by karthik137** [PolymathNetwork/Polymesh#1056]
I am new to polymesh. I have downloaded the binary and started a dev node. I am able to connect to the dev node using polymesh explorer.  But polyx transfer does not work. 

Following is the error message:

```
system.ExtrinsicFailed
balances.ReceiverCddMissing
```

Attaching screenshots

![accounts_sendfunds](https://user-images.githubusercontent.com/19289544/126981277-f7250563-7b8c-4770-b934-d67ae1a98876.png)
![authorize_transaction](https://user-images.githubusercontent.com/19289544/126981281-10e32894-3ccb-43da-907e-8d331299ed1a.png)
![error_polymesh_transfer](https://user-images.githubusercontent.com/19289544/126981405-c3efd25e-4519-4a64-a5af-03d07fa27fda.png)

How do i fix this issue? Please help.

**Comment by Neopallium** [comment]
The account `DAVE` doesn't have a CDD on your dev node.  That is what the `balances.ReceiverCddMissing` error means.

For testing you can add a CDD by callingthe `testUtils.mockCddRegisterDid` extrinsic.  Use account `ALICE` to call it and pass account `DAVE`.

That should allow Dave to receive Polyx.

**Comment by karthik137** [comment]
Thanks @Neopallium . It worked.
