### ISSUE TITLE
[Question] Why is the number of coins growing?

### ISSUE THREAD

**Issue by GitJhopa** [PolymathNetwork/Polymesh#1550]
I don’t understand why the number of coins is growing, but you yourself are lowering the price of your cryptocurrency. How many coins will your cryptocurrency grow to?

**Comment by F-OBrien** [comment]
New tokens are minted at a variable rate as rewards as part of the proof of stake consensus mechanism that is used to secure the chain. There is no upper limit on tokens but inflation does reduce over time as per the protocol.
