### ISSUE TITLE
[Question] When will there be a coin burning?

### ISSUE THREAD

**Issue by GitJhopa** [PolymathNetwork/Polymesh#1551]
I watch POLYX USDT and see that the number of Circulating supply coins is growing every day, thereby the price of the cryptocurrency is falling. I would like to know when new coins will stop being issued or existing ones will be burned so that the price of cryptocurrency will rise and not fall?

**Comment by F-OBrien** [comment]
This is not an issue with the repository so is being closed. Please use discord if you wish to ask questions. There is no plan to stop minting tokens as part of PoS or introduce a burning mechanism. https://discord.gg/polymesh
