### ISSUE TITLE
MESH-975 ⁃ external contributors

### ISSUE THREAD

**Issue by sbsends** [PolymathNetwork/Polymesh#360]
Hey 👋

I would like to contribute to the polymesh project. What are some good first issues?

**Comment by adamdossa** [comment]
Hi @sbsends - a good place to start is to make sure you can compile and run the node software (see README.md for instructions). You can also take a look at some of the javascript test scripts under scripts/cli for some ways to start executing actions on the blockchain.

If you'd like early access and more information of ways to get involved in the public testnet, you can sign up here:
https://polymath.network/beta-testing-community

**Comment by sbsends** [comment]
Hey @adamdossa - I was able to run the node, and signed up for the beta. 👍

<img width="1680" alt="Screen Shot 2020-05-08 at 6 24 20 PM" src="https://user-images.githubusercontent.com/21231577/81456824-7b00fa80-9159-11ea-9f69-c8ec992d264c.png">

<img width="1680" alt="Screen Shot 2020-05-08 at 6 24 23 PM" src="https://user-images.githubusercontent.com/21231577/81456827-7d635480-9159-11ea-8772-8cf3ad01386a.png">

Where can I help?
