### ISSUE TITLE
polymesh alcyone node crashes

### ISSUE THREAD

**Issue by paddyson79** [PolymathNetwork/Polymesh#653]
when I start the polymesh alcyone node it crashes and I get the following errors

> Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.593 main INFO polymesh::command  Reserved nodes: []
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  Polymesh Node
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  ✌️  version 2.0.0
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  ❤️  by Anonymous, 2017-2020
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  📋 Chain specification: Polymesh Alcyone Testnet
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  🏷  Node name: pathrock
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  👤 Role: AUTHORITY
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  💾 Database: RocksDb at /root/.local/share/polymesh/chains/alcyone/db
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.594 main INFO sc_cli::runner  ⛓  Native runtime: polymesh-2000 (polymath-polymesh-0.tx1.au1)
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.649 main INFO sub-libp2p  🏷  Local node identity is: 12D3KooWJkY8di7yUCLhrNVwPoxm26fbEEoaZBW6SbNdX3QxipKo (legacy representation: QmSkJyXwgs5NBzqVndL55xsQSZsBNzan3QNmFpcDteqFmJ)
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.659 main INFO sc_service::builder  📦 Highest known block at #1008
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.660 tokio-runtime-worker INFO substrate_prometheus_endpoint::known_os  〽️ Prometheus server started at 127.0.0.1:9615
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.664 main WARN sc_service  Unable to bind RPC server to 0.0.0.0:9933. Trying random port.
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.673 main WARN sc_service  Unable to bind RPC server to 127.0.0.1:9944. Trying random port.
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.676 main INFO babe  👶 Starting BABE Authorship worker
Oct 02 18:57:06 vmd48751.contaboserver.net polymesh[8369]: 2020-10-02 18:57:06.678 tokio-runtime-worker ERROR sub-libp2p  📪 Libp2p listener () closed: Address already in use (os error 98)
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]: ====================
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]: Version: 2.0.0
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    0: sp_panic_handler::set::{{closure}}
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    1: std::panicking::rust_panic_with_hook
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:              at /rustc/d6953df14657f5932270ad2b33bccafe6f39fad4/src/libstd/panicking.rs:530
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    2: std::panicking::begin_panic
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    3: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllModules,COnRuntimeUpgrade>::execute_block
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    4: <polymesh_runtime_testnet::runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<<pallet_indices::Module<polymesh_runtime_testnet::runtime::Runtime> as sp_runtime::traits::StaticLookup>::Source,polymesh_runtime_testnet::runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<polymesh_runtime_testnet::runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<polymesh_runtime_testnet::runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<polymesh_runtime_testnet::runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<polymesh_runtime_testnet::runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<polymesh_runtime_testnet::runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<polymesh_runtime_testnet::runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<polymesh_runtime_testnet::runtime::Runtime>,pallet_permissions::StoreCallMetadata<polymesh_runtime_testnet::runtime::Runtime>)>>>>::execute_block
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    5: sp_api::runtime_decl_for_Core::execute_block_native_call_generator::{{closure}}
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    6: std::thread::local::LocalKey<T>::with
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    7: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    8: sc_executor::wasm_runtime::RuntimeCache::with_instance
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:    9: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   10: sp_state_machine::StateMachine<B,H,N,Exec>::execute_aux
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   11: sp_state_machine::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   12: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   13: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   14: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   15: sp_api::Core::execute_block_with_context
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   16: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import_block
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   17: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImport<Block>>::import_block
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   18: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::import_block
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   19: sp_consensus::import_queue::import_single_block_metered
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   20: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   22: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   23: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   24: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   25: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   27: std::thread::local::LocalKey<T>::with
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   28: futures_executor::local_pool::block_on
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   29: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   30: std::panicking::try
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   31: tokio::runtime::task::harness::Harness<T,S>::poll
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   32: tokio::runtime::blocking::pool::Inner::run
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   33: tokio::runtime::context::enter
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   34: std::sys_common::backtrace::__rust_begin_short_backtrace
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   35: core::ops::function::FnOnce::call_once{{vtable.shim}}
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   36: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:              at /rustc/d6953df14657f5932270ad2b33bccafe6f39fad4/src/liballoc/boxed.rs:1081
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:       <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:              at /rustc/d6953df14657f5932270ad2b33bccafe6f39fad4/src/liballoc/boxed.rs:1081
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:       std::sys::unix::thread::Thread::new::thread_start
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:              at /rustc/d6953df14657f5932270ad2b33bccafe6f39fad4/src/libstd/sys/unix/thread.rs:87
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   37: start_thread
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:   38: __clone
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]: Thread 'tokio-runtime-worker' panicked at 'InvalidTransaction custom error', /rustc/d6953df14657f5932270ad2b33bccafe6f39fad4/src/libstd/macros.rs:13
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]: This is a bug. Please report it at:
Oct 02 18:57:07 vmd48751.contaboserver.net polymesh[8369]:         https://github.com/PolymathNetwork/polymesh/issues/new

>

have you got a fix for this?

**Comment by maxsam4** [comment]
Hey @paddyson79 , Thanks for reporting. It seems like you are running a node that is not targetted for Alcyone. 

Please download the latest Alcyone node from https://github.com/PolymathNetwork/Polymesh/releases or compile it from the `alcyone` branch.

Once you have the new node, please delete the database created by the old node by running `./polymesh purge-chain`. After that, you should be able to sync with Alcyone network by running `./polymesh`.

**Comment by paddyson79** [comment]
Hey Mudit Gupta,
got the node up and running, but on version 2.0.0 currently and not sure
why updating to version 2.0.2 didn't work yet.

Best regards,

Patrick

**Comment by maxsam4** [comment]
Good to hear that you got it working.

2.0.2 on the `develop` branch is actually ahead of 2.0.2 used on Alcyone and that's why you must've faced the issue. We'll update the readme to make the versioning differences between Alcyone and develop branch more clear.

FWIW, Polymesh supports onchain upgrades so even if you might be running 2.0.0 binary, you are actually using 2.0.3 runtime under the hood.

**Comment by paddyson79** [comment]
ok great - is there a command you can provide to get the session key from the node?

**Comment by maxsam4** [comment]
> ok great - is there a command you can provide to get the session key from the node?

You can run the following command to generate a fresh set of session keys:
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}' http://localhost:9933
```
You will get an output similar to:
```
{"jsonrpc":"2.0","result":"0x2bd908203ae740b513f5907fdcc2e29a6bd2835618da917c03d2cfe65d96745b54d59fe4dc5a106c130be0e677596eb023164c314d6fb5cc62ead1bcaee6a443fe5df859fc1de372580abaa98a22fee962bcff580bf57138adc12955aa698a5faa923978d9c16014205af96da9d2e213083aefcb53982927a2756ffa83d81658","id":1}
```
The “result” field contains the public key of your session keys.
```
0x2bd908203ae740b513f5907fdcc2e29a6bd2835618da917c03d2cfe65d96745b54d59fe4dc5a106c130be0e677596eb023164c314d6fb5cc62ead1bcaee6a443fe5df859fc1de372580abaa98a22fee962bcff580bf57138adc12955aa698a5faa923978d9c16014205af96da9d2e213083aefcb53982927a2756ffa83d81658
```

Please keep in mind that operators/validators on Polymesh are regulated entities and you will not be able to operate/validate without the governance council's explicit permission.

**Comment by paddyson79** [comment]
Hello Mudit,
I was trying the command you sent me to create the session keys, but
somehow it won't work.

Just wanted to give you this feedback.

Kind regards,

Patrick
