### ISSUE TITLE
Unknown error: Client(UnknownBlock("State already discarded for BlockId::Hash

### ISSUE THREAD

**Issue by achiko** [PolymathNetwork/Polymesh#655]
After connecting from Polymesh SDK  getting following error in terminal : 
....
**2020-10-03 21:11:00 Unknown error: Client(UnknownBlock("State already discarded for BlockId::Hash(0x12fddc9e2128b3fe571e4e5427addcb87fcaf08493867a68dd6ae44b406b39c7)"))**

Screen attached: 

![image](https://user-images.githubusercontent.com/3051858/95000018-51e07b00-05ce-11eb-9560-d2542236240d.png)

**Client Code :**  

```
 const polyClient = await Polymesh.connect({
    nodeUrl: "ws://<my node ip>:9944",
    accountSeed: seed,
  });

  console.log(
    "Block Number   : - ",
    new BigNumber(await polyClient.getLatestBlock()).toNumber()
  );

```
API returned response correctly but getting this message : 

**RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: -32603: Unknown error occurred: Client(UnknownBlock("State already discarded for BlockId::Hash(0x12fddc9e2128b3fe571e4e5427addcb87fc**

Screen : 

![image](https://user-images.githubusercontent.com/3051858/95000110-f662bd00-05ce-11eb-8ce6-cae46f604fad.png)

**Comment by maxsam4** [comment]
The SDK requires an archive node instead of a full node. To run your node in archive mode, you'd need to purge the chain using
```
./polymesh purge-chain
```
and then sync it again in pruning mode by using
```
./polymesh --pruning=archive
```
While your local node syncs, you can use this RPC endpoint: `wss://alcyone-rpc.polymesh.live/`

**Comment by achiko** [comment]
Thank you , The problem is solved.
